spring.datasource.url=jdbc:postgresql://localhost:5432/training
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
application.security.jwt.secret-key=SWFtZ2hhbnNoeWFtdmFnaGVsYWZyb21uYWdhcnJvdHJhaW5pbmdzZWNyZXRrZXk=
applicatoin.security.jwt.token.expiration=3600000
application.security.jwt.refresh-token.expiration=7200000
eureka.client.service-url.http.defaultZone=http://localhost:8761/eureka
