spring.datasource.url=jdbc:postgresql://localhost:5432/training
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
application.security.jwt.secret-key=SWFtZ2hhbnNoeWFtdmFnaGVsYWZyb21uYWdhcnJvdHJhaW5pbmdzZWNyZXRrZXk=
applicatoin.security.jwt.token.expiration=3600000
application.security.jwt.refresh-token.expiration=7200000
eureka.client.service-url.http.defaultZone=http://localhost:8761/eureka
spring.cloud.gateway.server.webmvc.routes[0].id=user-service
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8080
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/user-service/**
spring.cloud.gateway.server.webmvc.routes[0].filters[0]=RewritePath=/user-service/(?<segment>.*), /${segment}
